name: Comment on PR with Changed Files
on:
  pull_request:
    branches:
      - production

jobs:
  comment-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate changed files list
        run: git diff --name-only origin/production...$PR_NUMBER > changed_files.txt

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Execute comment-on-pr.js
        run: node .github/workflow-scripts/review-links.js
